### ISSUE TITLE
On Android, IP Camera lite protects rtsp stream with login/pwd

### ISSUE THREAD

**Issue by kartben** [ebertrams/iotedge-iva-nano#14]
We may want to recommend a different tool for android, as by default it seems to protect the rtsp stream behind a login password, which could complexify us documenting the proper steps to follow there

**Comment by emmanuel-bv** [comment]
Yeah, this is unfortunate but it is still the simplest tool that I have found that works on Android and iPhone and that is free. Instructions already mention removing the username and password. Feel free to update the instructions if you find a better tool.
One tool that I spent some time on but could not get to work robustly is a container with an embedded video file that streams it over RTSP. It sounds like a simple tool but I could not find any robust one. The best i found so far are these ones but they do crash too often, not reliable enough even just for a workshop: https://github.com/Ullaakut/RTSPAllTheThings and https://github.com/EasyMile/ez-rtsp-server/tree/master/lib. This solution would ideal though since you could simulate cameras on demand with Azure , also making it super useful for testing and developing.  I built a small ARM script that launches as many container instances as you need. Thi spart is easy but a simple RTSP server that streams from an hardcoded video seems more difficult to get right.
