### ISSUE TITLE
New IoT Edge Module

### ISSUE THREAD

**Issue by Y07yoyo** [ebertrams/iotedge-iva-nano#42]
Hi @ebertrams and @sseiber 

I am trying to create a new IoT Edge Module where I can access some API to get some data and construct a message and send it to the IoTCentralBridge module. I have tried using Vscode (Right click deployment.json -> Add IoTEdge Module)  but the templates that open are listening for an input where as the module I am creating wont be listening for an input, rather just be sending output messages.

A bit like the simulatedTemperature module, where it is not listening to an input, rather only sending an output for the IoTCentralBridge Module to process the message and send it to the cloud.

Can you give me some insights as to how I can do this?

Kind Regards,

Yusuf

**Comment by emmanuel-bv** [comment]
hi @Y07yoyo , you can have a look at this new documentation https://github.com/rangv/azureiotcentraledgelinux that shows you how to templatize your telemetry ONCE received in central (as opposed to in the client like this repo does since it was the only option before). @rangv is from the IoT Central team and can provide you additional guidance if required. Thanks
